### ISSUE TITLE
Latest tag to fetch the last build from master

### ISSUE THREAD

**Issue by muvaf** [crossplane/cicd#1]
I think it'd be great if we can use `latest` image tag to pull the latest build from master as this is kind of the pattern that most projects use. Maybe we can add a `stable` tag, too, for the latest actual release to be pulled.

cc @suskin

**Comment by muvaf** [comment]
@suskin I stand corrected. It seems that `latest` seems to be used to point to the latest **release** while there is not so much of a consensus. See [wordpress](https://hub.docker.com/_/wordpress/) image.

Image built the most recently on `master` branch could be tagged with `master` tag I guess; no confusion for anyone.

**Comment by suskin** [comment]
The `master` tag part of this is fixed by #2 , though there is still some cleanup to do to remove the existing `latest` tags for all of the stacks (as that is the [prevailing pattern](https://hub.docker.com/repository/registry-1.docker.io/crossplane/stack-aws/tags?page=1&name=latest) for our stack repositories). I'll close this once that's done.

**Comment by muvaf** [comment]
@suskin thanks for tackling this!

**Comment by suskin** [comment]
All of the `latest` tags have been deleted now from the minimal stacks and the wordpress stack, so I'm going to close this issue.
